<?php

// Create our custom group and fields
return array(
  0 => array(
    'entity' => 'CustomGroup',
    'name' => 'turnout_fields',
    'update' => 'never',
    'params' => array (
      'version' => 3,
      'is_active' => 1,
      'name' => 'turnout_fields',
      'title' => 'Turnout Fields',
      'extends' => 'Participant',
      'extends_entity_column_id' => '2',
      'style' => 'inline',
      'collapse_display' => '0',
      'is_active' => '1',
      'is_multiple' => '0',
      'collapse_adv_display' => '0',
      'is_reserved' => '0',
      'is_public' => '1',
      'api.custom_field.create' => array(
        array(
          'custom_group_id' => '$value.id',
          'label' => 'Invitation Date',
          'name' => 'turnout_invitation_date',
          'data_type' => 'Date',
          'html_type' => 'Select Date',
          'is_required' => '0',
          'is_searchable' => '1',
          'is_search_range' => '1',
          'weight' => '40',
          'is_active' => '1',
          'is_view' => '0',
          'text_length' => '255',
          'start_date_years' => '30',
          'date_format' => 'mm/dd/yy',
          'note_columns' => '60',
          'note_rows' => '4',
          'in_selector' => '0'
        ),
        array(
          'custom_group_id' => '$value.id',
          'label' => 'Invitation Response',
          'name' => 'turnout_invitation_response',
          'data_type' => 'String',
          'html_type' => 'Select',
          'is_required' => '0',
          'is_searchable' => '1',
          'is_search_range' => '0',
          'weight' => '40',
          'is_active' => '1',
          'is_view' => '0',
          'in_selector' => '0'
        ), 
        array(
          'custom_group_id' => '$value.id',
          'label' => 'Second Call Date',
          'name' => 'turnout_second_call_date',
          'data_type' => 'Date',
          'html_type' => 'Select Date',
          'is_required' => '0',
          'is_searchable' => '1',
          'is_search_range' => '1',
          'weight' => '40',
          'is_active' => '1',
          'is_view' => '0',
          'text_length' => '255',
          'start_date_years' => '30',
          'date_format' => 'mm/dd/yy',
          'note_columns' => '60',
          'note_rows' => '4',
          'in_selector' => '0'
        ),
        array(
          'custom_group_id' => '$value.id',
          'label' => 'Second Call Response',
          'name' => 'turnout_second_call_response',
          'data_type' => 'String',
          'html_type' => 'Select',
          'is_required' => '0',
          'is_searchable' => '1',
          'is_search_range' => '0',
          'weight' => '40',
          'is_active' => '1',
          'is_view' => '0',
          'in_selector' => '0'
        ),
        array(
          'custom_group_id' => '$value.id',
          'label' => 'Reminder Date',
          'name' => 'turnout_reminder_date',
          'data_type' => 'Date',
          'html_type' => 'Select Date',
          'is_required' => '0',
          'is_searchable' => '1',
          'is_search_range' => '1',
          'weight' => '40',
          'is_active' => '1',
          'is_view' => '0',
          'text_length' => '255',
          'start_date_years' => '30',
          'date_format' => 'mm/dd/yy',
          'note_columns' => '60',
          'note_rows' => '4',
          'in_selector' => '0'
        ),
        array(
          'custom_group_id' => '$value.id',
          'label' => 'Reminder Response',
          'name' => 'turnout_reminder_response',
          'data_type' => 'String',
          'html_type' => 'Select',
          'is_required' => '0',
          'is_searchable' => '1',
          'is_search_range' => '0',
          'weight' => '40',
          'is_active' => '1',
          'is_view' => '0',
          'in_selector' => '0'
        ),
      ),
    ),
  ),
  2 => array(
    'entity' => 'OptionGroup',
    'name' => 'turnout_invite_response_values',
    'update' => 'never',
    'params' => array (
      'version' => 3,
      'name' => 'turnout_invite_response_values',
      'title' => 'Invitation Response Values',
      'is_reserved' => '1',
      'is_active' => '1',
      'is_locked' => '0',
      'api.option_value.create' => array(
        array(
          'option_group_id' => '$value.id',
          'label' => 'Yes',
          'name' => 'turnout_response_yes',
          'value' => '1',
          'is_default' => '0',
          'weight' => '10',
          'is_optgroup' => '0',
          'is_reserved' => '0',
          'is_active' => '1'
        ),
        array(
          'option_group_id' => '$value.id',
          'label' => 'No',
          'name' => 'turnout_response_nno',
          'value' => '2',
          'is_default' => '0',
          'weight' => '20',
          'is_optgroup' => '0',
          'is_reserved' => '0',
          'is_active' => '1'
        ),
        array(
          'option_group_id' => '$value.id',
          'label' => 'Left Message',
          'name' => 'turnout_response_left_message',
          'value' => '3',
          'is_default' => '0',
          'weight' => '30',
          'is_optgroup' => '0',
          'is_reserved' => '0',
          'is_active' => '1'
        ),
        array(
          'option_group_id' => '$value.id',
          'label' => 'Not Home',
          'name' => 'turnout_response_not_home',
          'value' => '4',
          'is_default' => '0',
          'weight' => '40',
          'is_optgroup' => '0',
          'is_reserved' => '0',
          'is_active' => '1'
        ),
      ),
    ),
  ),
);
